USE login-simples;

DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(150) NOT NULL,
	senha varchar(255) NOT NULL
);

SELECT * FROM USUARIO;